{% set version = "0.1-3.1" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tsne
  version: {{ version|replace("-", "_") }}

source:
  fn: tsne_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/tsne_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/tsne/tsne_{{ version }}.tar.gz
  sha256: 14abc65bc0a3f3ed63c04dda19620e483a21d1f5f33feb74aba9f3221434d888

build:
  noarch: generic
  number: 0

  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - r-base

  run:
    - r-base

test:
  commands:
    - $R -e "library('tsne')"  # [not win]
    - "\"%R%\" -e \"library('tsne')\""  # [win]

about:
  home: https://github.com/jdonaldson/rtsne/
  license: GPL
  summary: A "pure R" implementation of the t-SNE algorithm.
  license_family: GPL

  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3
extra:
  recipe-maintainers:
    - conda-forge/r
    - dpryan79
    - johanneskoester
    - bgruening
    - daler
