appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: czpoe8p+F2VCr3OHyOLTcX4VagcAHz0DJPBtk1pQrDdzYDa9N7lUb28LU/soQ+mS7cAkmTdbE1zcFp6pyYTr7psufu/FiRzBA346s40qFJcjHyYpNqKVRCYGv/9xK9FTkxr7Rmr70LWtPmnaWu9guYBQ1ft5UAK+gB6I08o3eesAAGVXsxr2nqP6uEnl5FrkaqCg2c5bcTns87fHNxYwaQ3ZkApV7qWpomgWycV0wFFVHn2hTSp0Pt4uiqtLpbsYm9IJNApX7/7s8iDey8wlL9O9RzrhEkh+hocWr+Jc5JH/xjLHH5yITi6LdbiPKHFV5q8vJVcpTxvss5+E//iamnBPDrzh6K1TaiddnrJtJwDgOpVMUpQacUOUNkgIoeKIRoOcIXCExTnVe6c3JsVdpnGv7S07mWm3O4DxAYfUc+0LQT8UPVUjD876kvZOioL1BgtaITmCMd7VOp4WTFDlo0ztFjixFwEODBlfLXOiO2L7WwkYixop/S42g57BxMPyvb8VnnEMh4UsHUwDFngdbT9bgCAgJYxAW9CdvuTqSGfrNoPTTLemAdhUfaWP4d7zL6jaHfggvXp5ZrY/qdoB5/xzDcd0g31ykEim2KXncoZP5I1wraSC7BWCR9sE8Lu4f/ApbUSxf+2khWeb6/RTp2ZeWdgkya/IrsKxK/3FO3w=}
