travis:
  secure:
    BINSTAR_TOKEN: hJDud2WpGpnjXRy9hj4d02eefThYer7DWaXgxfGSq57UmADpPB6mMi0Oz+mRBPAT+U64bto9XU0x2SYEi/hvPwv5trCVs+5ISOttgbqqJD2mAUOQvA5VyBjFwTafEV3wH3n+ozqvateczuq7VZ0khtRQNETGRPzvAy0P15pDcscsWNrHgrbhh0ZNOgEm69ag2O+MtpallnVu1FCVrD2k4YLu24Pcy4hp0csI8QgilQbpkzCBozLFbicMlTigiMD67VDCHZaAKgdSvKeOR95+BkkcUd2nvGo+OBLhZ/z05qOM5Hb8giAoFO4Ls8wqCpw6+23mVPexWckZGJaqbHIZzixOrwPGMWiqFFpGoSt3Y3iUEYvQ8YPlYP7n3dssYbLJAa3Xu/CEKquLVRMbjnxfL5uLfkypSDO0+eE2TBIDoc3qnBEJTUsf6SuYwG6H8k265NJW/yUOTBST5EhixIIOQADjEvExLidYU/totDO2VpGghvrGBrAtKgy5zbsFY88hfZs0VogmxB7ENT45twV9ZSKKFlBFB15WpWxXNcEWsCy/MN/+kiN5MYC/MroQxAZyL2KCiF3cDB9DxEFwSCa2enpGk0ne75dKBS5DBcc9Ifpr5t4NfwY03K6CG3KGR8RmghXDrq3UOEn4dFMU0ecUs6fhwSFYtoLy/xxqlXVO3zQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
